<?php
/**
 * Brand tip-board meta (URL slug = /api/{slug}).
 * Unique SEO HTML lives in pages/brand-seo/{slug}.php — not a shared helper.
 * Each page gets its own fixture slate via board_key in config/api-pages.php.
 *
 * `intro` may contain trusted HTML (<strong>, <a>) — rendered in the hero.
 */
return [

    'betensured-predictions' => [
        'brand' => 'Betensured',
        'title' => 'Betensured Predictions Today, Betensured Tips & Football Analysis',
        'description' => 'Betensured Predictions Today, Betensured Tips & Football Analysis',
        'keywords' => 'betensured, betensured prediction, betensured prediction today, betensured today, betensured tips',
        'h1' => 'Betensured Predictions Today - Football Tips, Analysis & Betensured Tips',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Betensured Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'betpera-predictions' => [
        'brand' => 'Betpera',
        'title' => 'Betpera Predictions Today, Betpera Tips & Football Analysis',
        'description' => 'Betpera Predictions Today, Betpera Tips & Football Analysis',
        'keywords' => 'betpera, betpera prediction, betpera tips, betpera prediction today, betpera predictions',
        'h1' => 'Betpera Predictions Today - Football Tips, Analysis & Betpera Tips',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Betpera Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'forebet-predictions' => [
        'brand' => 'Forebet',
        'title' => 'Forebet Predictions Today, Forebet Tips & Football Analysis',
        'description' => 'Forebet Predictions Today, Forebet Tips & Football Analysis',
        'keywords' => 'forebet, forebet today, forebet prediction, forebet mega jackpot prediction, forebet prediction today, zulubet predictions for today forebet, forebet today prediction, forebet today prediction tips, mega jackpot prediction 17 games today forebet, forebet tomorrow, forebet midweek jackpot predictions, sure mega jackpot predictions this weekend forebet, forebet predictions',
        'h1' => 'Forebet Predictions Today - Football Tips, Analysis & Forebet Today Prediction',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Forebet Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'zulubet-predictions' => [
        'brand' => 'Zulubet',
        'title' => 'Zulubet Predictions Today, Zulubet Tips & Football Analysis',
        'description' => 'Zulubet Predictions Today, Zulubet Tips & Football Analysis',
        'keywords' => 'zulubet, zulubet mega jackpot prediction, zulubet predictions for today forebet, zulubet prediction, zulubet midweek jackpot prediction',
        'h1' => 'Zulubet Predictions Today - Football Tips, Mega Jackpot & Forebet Comparison',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Zulubet Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'mighty-tips' => [
        'brand' => 'Mighty Tips',
        'title' => 'Mighty Tips Predictions Today, MightyTips Tips & Football Analysis',
        'description' => 'Mighty Tips Predictions Today, MightyTips Tips & Football Analysis',
        'keywords' => 'mighty tips, mighty tips prediction, mighty tips today, mighty tips predictions, mighty tips correct score, mightytips, mightytips today',
        'h1' => 'Mighty Tips Predictions Today - Football Tips, MightyTips Today & Correct Score',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Mighty Tips',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'mwanasoka-tips' => [
        'brand' => 'Mwanasoka',
        'title' => 'Mwanasoka Tips Today, Mwanasoka Predictions & Football Analysis',
        'description' => 'Mwanasoka Tips Today, Mwanasoka Predictions & Football Analysis',
        'keywords' => 'mwanasoka tips, mwanasoka, mwanasoka prediction, mwanasoka tips today, mwanasoka mega jackpot prediction',
        'h1' => 'Mwanasoka Tips Today - Mwanasoka Predictions & Mega Jackpot Tips',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Mwanasoka Tips',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'predictz-tips' => [
        'brand' => 'PredictZ',
        'title' => 'PredictZ Today, PredictZ Tips & Football Analysis',
        'description' => 'PredictZ Today, PredictZ Tips & Football Analysis',
        'keywords' => 'predictz, predictz today, 100 predictz, victor predictz, surebet predictz',
        'h1' => 'PredictZ Today - Football Tips, 100 PredictZ & Surebet PredictZ',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'PredictZ Tips',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'primatips-prediction' => [
        'brand' => 'PrimaTips',
        'title' => 'PrimaTips Predictions Today, PrimaTips Tips & Football Analysis',
        'description' => 'PrimaTips Predictions Today, PrimaTips Tips & Football Analysis',
        'keywords' => 'primatips, primatips today, primatips prediction',
        'h1' => 'PrimaTips Predictions Today - Football Tips & PrimaTips Today',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'PrimaTips Prediction',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'solo-prediction' => [
        'brand' => 'Solo Prediction',
        'title' => 'Solo Prediction Today, Solo Tips & Football Analysis',
        'description' => 'Solo Prediction Today, Solo Tips & Football Analysis',
        'keywords' => 'solo prediction, solo prediction for today, solo prediction today, solo prediction correct score, sure win 100 solo prediction',
        'h1' => 'Solo Prediction Today - Football Tips, Correct Score & Sure Win 100',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Solo Prediction',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'statarea-predictions' => [
        'brand' => 'Statarea',
        'title' => 'Statarea Predictions Today, Statarea Tips & Football Analysis',
        'description' => 'Statarea Predictions Today, Statarea Tips & Football Analysis',
        'keywords' => 'statarea, statarea prediction, old statarea, statarea prediction today, old statarea prediction today, statarea old, statarea mega jackpot prediction, statarea prediction today 1x2, statarea today, statarea midweek jackpot prediction, statarea zulubet today, old statarea prediction',
        'h1' => 'Statarea Prediction Today 1X2 - Football Tips, Old Statarea & Mega Jackpot',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Statarea Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'supatips-prediction' => [
        'brand' => 'Supatips',
        'title' => 'Supatips Predictions Today, Supatips Tips & Football Analysis',
        'description' => 'Supatips Predictions Today, Supatips Tips & Football Analysis',
        'keywords' => 'supatips, supatips mega jackpot prediction, supatips prediction today, supatips today',
        'h1' => 'Supatips Predictions Today - Football Tips & Mega Jackpot Prediction',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Supatips Prediction',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'tips180-predictions' => [
        'brand' => 'Tips180',
        'title' => 'Tips180 Predictions Today, Tips180 Double Chance & Football Tips',
        'description' => 'Tips180 Predictions Today, Tips180 Double Chance & Football Tips',
        'keywords' => 'tips180, victorpredict tips180, tips180 prediction, tips180 double chance, tips180 correct score',
        'h1' => 'Tips180 Predictions Today - Double Chance Tips & Victor Predict Tips180',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Tips180 Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'victorspredicts' => [
        'brand' => 'Victor Prediction',
        'title' => 'Victor Prediction Today, Victor Predict Tips & Football Analysis',
        'description' => 'Victor Prediction Today, Victor Predict Tips & Football Analysis',
        'keywords' => 'victor prediction, victor prediction today, victor prediction for today, victor prediction correct score',
        'h1' => 'Victor Prediction Today - Football Tips & Victor Prediction Correct Score',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'Victor Prediction',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'vitibet-predictions' => [
        'brand' => 'Vitibet',
        'title' => 'Vitibet Predictions Today, Vitibet Tips & Football Analysis',
        'description' => 'Vitibet Predictions Today, Vitibet Tips & Football Analysis',
        'keywords' => 'vitibet predictions, vitibet prediction today, vitibet today, today vitibet, vitibet football, vitibet sure wins, vitibet prediction football, vitibet prediction for next 7 days, vitibet tips of the day',
        'h1' => 'Vitibet Predictions Today - Football Tips, Analysis & Vitibet Football',
        'intro' => '<a href="/">Vitibet predictions</a> are football tips for upcoming matches. Football fans and bettors looking for <strong>Vitibet prediction today</strong> can check recent form, team performance and match statistics. <strong>Vitibet football</strong> searches also cover different leagues and betting markets.',
        'intro_links' => '',
        'breadcrumb' => 'Vitibet Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'windrawwin-predictions' => [
        'brand' => 'WinDrawWin',
        'title' => 'WinDrawWin Predictions Today, WinDrawWin Tips & Football Analysis',
        'description' => 'WinDrawWin Predictions Today, WinDrawWin Tips & Football Analysis',
        'keywords' => 'windrawwin, windrawwin today prediction, windrawwin prediction, windrawwin predictions today',
        'h1' => 'WinDrawWin Predictions Today - WinDrawWin Today Prediction & Football Tips',
        'intro' => '',
        'intro_links' => '',
        'breadcrumb' => 'WinDrawWin Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    '1960-tips' => [
        'brand' => '1960 Tips',
        'title' => '1960 Tips Today, 1960 Predictions & Football Tips',
        'description' => '1960 Tips Today, 1960 Predictions & Football Tips',
        'keywords' => '1960 tips, 1960tips, 1960 predictions, 1960 tips prediction, tip 1960, tips1960, 1960 bet prediction, 1960 bet tip, 1960 prediction today, 1960 tip, 1960 tips correct score, 1960 tips today',
        'h1' => '1960 Tips - 1960 Predictions, Football Tips Today & Correct Score',
        'intro' => '<strong>1960 Tips</strong> and <strong>1960tips</strong> are football predictions, match tips and different prediction markets for matches across major leagues and competitions. <strong>1960 predictions</strong> can cover match results, goals, BTTS, Double Chance and correct score selections. At <a href="/">Bao Predictions</a>, our experienced tipsters and match analysts provide independent football predictions supported by match statistics and detailed analysis.',
        'intro_links' => '',
        'breadcrumb' => '1960 Tips',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'adibet-predictions' => [
        'brand' => 'Adibet',
        'title' => 'Adibet Predictions Today, Adi Bet Tips & Football Analysis',
        'description' => 'Adibet Predictions Today, Adi Bet Tips & Football Analysis',
        'keywords' => 'adibet, adibet predictions, adibet prediction today, adibet today, adibet mega jackpot prediction, adibet midweek jackpot prediction, adi bet, adibet gg prediction, adibet correct score, adi bet prediction, adi bet prediction today, adibet football predictions, adibet tips today, adibet tomorrow, adibet jackpot prediction',
        'h1' => 'Adibet Predictions Today - Football Tips, Analysis & Adi Bet Predictions',
        'intro' => '<a href="/">Adibet predictions</a> are football tips covering upcoming matches across different leagues and competitions. Football fans and bettors looking for <a href="/football-predictions-today">Adibet prediction today</a> can use match statistics, recent form, team performance and other available data to find reliable tips. Bao Predictions provides free football predictions across markets such as <a href="/1x2-predictions">1X2</a>, <a href="/btts-predictions">BTTS</a>, <a href="/over-under-predictions">Over/Under</a>, <a href="/double-chance-predictions">Double Chance</a> and HT/FT.',
        'intro_links' => '',
        'breadcrumb' => 'Adibet Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'betimate-predictions' => [
        'brand' => 'Betimate',
        'title' => 'Betimate Prediction Today, Betimate Football Predictions & Tips',
        'description' => 'Betimate Prediction Today, Betimate Football Predictions & Tips',
        'keywords' => 'betimate prediction, betimate prediction today, betimate today, betimate predictions, betimate predictions today, betimate com, betimate com prediction, betimate football prediction, betimate prediction for today, betimate prediction tomorrow, betimate today prediction, betimate tomorrow, www betimate prediction com',
        'h1' => 'Betimate Prediction - Betimate Today, Football Predictions & Tips',
        'intro' => '<strong>Betimate prediction</strong> covers football tips for today\'s matches, upcoming fixtures and different prediction markets. <strong>Betimate prediction today</strong> focuses on current fixtures, while <strong>Betimate today</strong> covers match results, statistics and football analysis. At Bao Predictions, our football analysts provide independent predictions based on team form, statistics, home and away records, head-to-head data and other match information.',
        'intro_links' => '',
        'breadcrumb' => 'Betimate Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'kingspredict-predictions' => [
        'brand' => 'KingsPredict',
        'title' => 'KingsPredict Today, Kings Prediction & Football Tips',
        'description' => 'KingsPredict Today, Kings Prediction & Football Tips',
        'keywords' => 'kingspredict, kings prediction, kings predict, kings prediction today, kingspredict today, king prediction tips, kings predict today, kings prediction correct score, kings prediction today football, kingspredict com, kingspredict ht ft, kingspredictions, kingspredicts',
        'h1' => 'KingsPredict - Kings Prediction Today, Football Tips & Correct Score',
        'intro' => '<strong>KingsPredict</strong> are football predictions, daily football tips and match prediction for different markets. <strong>Kings prediction</strong>  cover match results, goals, BTTS, Double Chance, Half-Time markets and Correct Score. At <a href="/">Bao Predictions</a>, our experienced tipsters and match analysts provide independent football predictions supported by team statistics, recent form and detailed match analysis.',
        'intro_links' => '',
        'breadcrumb' => 'KingsPredict Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'soccervista-predictions' => [
        'brand' => 'SoccerVista',
        'title' => 'SoccerVista Predictions Today, Soccer Tips & Football Analysis',
        'description' => 'SoccerVista Predictions Today, Soccer Tips & Football Analysis',
        'keywords' => 'SoccerVista prediction, SoccerVista predictions, SoccerVista prediction today, SoccerVista soccer prediction, SoccerVista soccer predictions today, SoccerVista today, SoccerVista today prediction, Soccer Vista soccer prediction, SoccerVista livescore, Soccer Vista live score, SoccerVista prediction tomorrow, SoccerVista weekend predictions, SoccerVista football predictions, SoccerVista football tips, SoccerVista match predictions, SoccerVista soccer tips, old SoccerVista, new SoccerVista',
        'h1' => 'SoccerVista Predictions Today - Football Tips, Analysis & Old vs New SoccerVista',
        'intro' => '<strong>SoccerVista predictions</strong> are football tips for upcoming matches including, today, tomorrow and the weekend. <a href="/"><strong>Bao Predictions</strong></a> provides all <strong>SoccerVista</strong> football tips, match statistics and analysis covering popular markets such as 1X2, double chance, BTTS, over/under goals and correct score. Our <strong>SoccerVista prediction</strong> is designed for users looking for football predictions, match analysis and statistical insights for upcoming games across leagues and competitions.',
        'intro_links' => '',
        'breadcrumb' => 'SoccerVista Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

    'zakabet-predictions' => [
        'brand' => 'Zakabet',
        'title' => 'Zakabet Predictions Today, Zaka Bet Tips & Football Predictions',
        'description' => 'Zakabet Predictions Today, Zaka Bet Tips & Football Predictions',
        'keywords' => 'zakabet predictions, zakabet prediction today, zakabet football predictions, zakabet tips, zaka bet, zakabets, zakabet today, zakabet single bet of the day, zakabet sure wins, zakabet correct score predictions, zakabet double chance predictions, zakabet prediction tomorrow, zakabet prediction for next 7 days, zakabet jackpot predictions',
        'h1' => 'Zakabet Predictions - Zaka Bet, Zakabets & Football Tips',
        'intro' => '<strong>Zakabet predictions</strong> cover football tips for today\'s matches, tomorrow\'s fixtures and upcoming games. <strong>Zaka Bet</strong> and <strong>Zakabets</strong> cover football matches from different leagues and competitions. At Bao Predictions, our <strong>Zakabet prediction today</strong> includes match results, goals, BTTS, Double Chance and other football tips based on form, statistics, team performance and expert analysis.',
        'intro_links' => '',
        'breadcrumb' => 'Zakabet Predictions',
        'sections' => ['prediction'],
        'related' => '',
    ],

];
