<?php
/** Market, accumulator, jackpot, and support page SEO blocks */
return [
    'accumulator-tips' => [
        'title' => 'Accumulator Tips Today | Bao Predictions',
        'description' => 'Free accumulator tips with combined odds for 3-fold, 5-fold and 8-fold accas. Updated daily from high-confidence picks.',
        'h1' => 'Accumulator Tips Today',
        'canonical' => '/accumulator-tips',
        'unique' => 'This page assembles real tickets — not a dump of singles. Decimal odds multiply across legs; one wrong pick voids the acca. Our 3-fold stays conservative; the 8-fold is labelled higher variance on purpose. Match ticket length to your bankroll and never chase losses with longer folds.',
        'related' => [
            ['Must-win teams today', '/must-win-teams-today'],
            ['How we predict', '/how-we-predict'],
            ['Today\'s predictions', '/football-predictions-today'],
        ],
        'faqs' => [
            ['q' => 'How do accumulator odds work?', 'a' => 'Multiply decimal odds of each leg. A 1.50 and 2.00 two-fold pays 3.00. One loser settles the whole ticket as lost.'],
            ['q' => 'Are your accumulators free?', 'a' => 'Yes. Ready-made tickets are free to view.'],
            ['q' => 'Should I stake big on an 8-fold?', 'a' => 'No. More legs means higher variance. Keep stakes small on long accas.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Accumulators', 'url' => '/accumulator-tips']],
    ],
    '1x2-predictions' => [
        'title' => '1X2 Predictions Today | Bao Predictions',
        'description' => '1X2 predictions for today — home, draw or away leans with confidence scores. Free match-result tips updated daily.',
        'h1' => '1X2 Predictions Today',
        'canonical' => '/1x2-predictions',
        'unique' => '1X2 is the classic full-time result market: 1 home, X draw, 2 away. Our confidence reflects how strongly we lean after form and price checks. Draws are harder to nail — we publish them when the data supports a stalemate, not to fill a card. For informational readers: you are predicting the 90-minute result including stoppage, not extra time unless the bookmaker says otherwise.',
        'related' => [
            ['Double chance predictions', '/double-chance-predictions'],
            ['Today\'s predictions', '/football-predictions-today'],
            ['How we predict', '/how-we-predict'],
        ],
        'faqs' => [
            ['q' => 'What does 1X2 mean?', 'a' => '1 = home win, X = draw, 2 = away win after 90 minutes plus stoppage.'],
            ['q' => 'Do you tip every match on 1X2?', 'a' => 'Only fixtures with a clear lean. Some games are better served by BTTS or over/under.'],
            ['q' => 'Are 1X2 predictions free?', 'a' => 'Yes.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => '1X2', 'url' => '/1x2-predictions']],
    ],
    'double-chance-predictions' => [
        'title' => 'Double Chance Predictions | Bao Predictions',
        'description' => 'Double chance predictions today — 1X, 12 or X2 covers with confidence ratings. Free two-way football tips.',
        'h1' => 'Double Chance Predictions',
        'canonical' => '/double-chance-predictions',
        'unique' => 'Double chance covers two of three outcomes (1X, X2, or 12). Odds are shorter because you hold more results. Use it when you like a side but want draw insurance — not as spam cover on every favourite. Classic jackpot cards usually still require straight 1X2; use DC on singles and smart singles books.',
        'related' => [
            ['1X2 predictions', '/1x2-predictions'],
            ['How to read BTTS odds', '/how-to-read-btts-odds'],
            ['Today\'s predictions', '/football-predictions-today'],
        ],
        'faqs' => [
            ['q' => 'What is 1X double chance?', 'a' => 'Home win or draw — the away team must not win.'],
            ['q' => 'Why are double chance odds lower?', 'a' => 'You cover two results, so the bookmaker shortens the price.'],
            ['q' => 'Is double chance good for jackpots?', 'a' => 'Most jackpots require straight 1X2. Use DC on single bets, not classic mega cards.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Double Chance', 'url' => '/double-chance-predictions']],
    ],
    'over-under-predictions' => [
        'title' => 'Over Under Predictions | Bao Predictions',
        'description' => 'Over under predictions and over 2.5 goals tips with confidence scores. Free O/U football predictions updated daily.',
        'h1' => 'Over Under Predictions',
        'canonical' => '/over-under-predictions',
        'unique' => 'When the match winner is murky but the scoring profile is clear, over/under is the better market. We lean over 2.5 when both attacks create chances; under when midfields clog and clean sheets are common — many Serie A and Kenya Premier League games skew under. Always confirm the line (2.5 vs 1.5/3.5) on your slip.',
        'related' => [
            ['BTTS predictions', '/btts-predictions'],
            ['Weekend predictions', '/weekend-football-predictions'],
            ['Today\'s predictions', '/football-predictions-today'],
        ],
        'faqs' => [
            ['q' => 'What is Over 2.5?', 'a' => 'You win if three or more goals are scored in 90 minutes.'],
            ['q' => 'Do you tip other goal lines?', 'a' => 'The public list focuses on 2.5; commentary may mention other lines when relevant.'],
            ['q' => 'Are over under predictions free?', 'a' => 'Yes.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Over/Under', 'url' => '/over-under-predictions']],
    ],
    'btts-predictions' => [
        'title' => 'BTTS Predictions Today | Bao Predictions',
        'description' => 'BTTS predictions and both teams to score tips today with confidence ratings. Free Yes/No leans updated daily.',
        'h1' => 'BTTS Predictions Today',
        'canonical' => '/btts-predictions',
        'unique' => 'Both Teams to Score (BTTS) wins when each side finds the net in 90 minutes. Yes thrives when both attacks convert; we lean No only with strong clean-sheet evidence. Cagey derbies can suppress scoring even when season averages look open — context beats raw averages. For a deeper walkthrough, read our guide on how to read BTTS odds.',
        'related' => [
            ['How to read BTTS odds', '/how-to-read-btts-odds'],
            ['Over/Under predictions', '/over-under-predictions'],
            ['Today\'s predictions', '/football-predictions-today'],
        ],
        'faqs' => [
            ['q' => 'What does BTTS mean?', 'a' => 'Both Teams to Score — each team scores at least once in 90 minutes.'],
            ['q' => 'Is BTTS good for accumulators?', 'a' => 'It can be, but correlated high-scoring games can fail together — size stakes carefully.'],
            ['q' => 'Where can I learn more about BTTS odds?', 'a' => 'See our blog post: How to read BTTS odds.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'BTTS', 'url' => '/btts-predictions']],
    ],
    'ht-ft-predictions' => [
        'title' => 'HT FT Predictions | Bao Predictions',
        'description' => 'HT FT predictions and half time full time tips. Selective HT/FT leans with confidence scores, free on Bao.',
        'h1' => 'HT FT Predictions',
        'canonical' => '/ht-ft-predictions',
        'unique' => 'Half-time/full-time (HT/FT) asks you to get both the break and the final 1X2 right — for example 1/1 means home leading at half-time and winning full-time. It pays more because two results must land. We publish sparsely, usually for home favourites that start fast.',
        'related' => [
            ['1X2 predictions', '/1x2-predictions'],
            ['Today\'s predictions', '/football-predictions-today'],
            ['Accumulator tips', '/accumulator-tips'],
        ],
        'faqs' => [
            ['q' => 'What does 1/1 mean in HT/FT?', 'a' => 'Home team leading at half-time and winning at full-time.'],
            ['q' => 'Is HT/FT riskier than 1X2?', 'a' => 'Yes — two results must land, so hit rates are lower and odds are higher.'],
            ['q' => 'Are HT FT tips free?', 'a' => 'Yes.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'HT/FT', 'url' => '/ht-ft-predictions']],
    ],
    'jackpot-predictions' => [
        'title' => 'Jackpot Predictions This Week | Bao Predictions',
        'description' => 'Football jackpot predictions this week — SportPesa Mega, Midweek, Betika, SportyBet Daily and Odibets Laki Tatu. Free sheets.',
        'h1' => 'Jackpot Predictions',
        'canonical' => '/jackpot-predictions',
        'unique' => 'A jackpot bet asks you to nail every result on a fixed multi-game card — often 15 or 17 matches for mega products, or as few as three for short-card offers like Laki Tatu. Prize pools grow with stakes; one wrong pick usually ends the jackpot win. That is why each Bao sheet shows confidence per game and fixture-specific reasoning, not a duplicated template. Use this hub to see which jackpots are open this week, then open the product page for the full ordered list.',
        'related' => [
            ['SportPesa Mega Jackpot', '/sportpesa-mega-jackpot-predictions'],
            ['Mega Jackpot strategy guide', '/mega-jackpot-strategy-guide'],
            ['Weekend predictions', '/weekend-football-predictions'],
        ],
        'faqs' => [
            ['q' => 'What is a football jackpot bet?', 'a' => 'A fixed multi-game ticket where you must correctly predict every listed 1X2 (or product-specific) result to win or share the pool.'],
            ['q' => 'Which jackpots does Bao cover?', 'a' => 'SportPesa Mega and Midweek, Betika Midweek, SportyBet Daily, and Odibets Laki Tatu — each on its own page.'],
            ['q' => 'Are jackpot predictions free?', 'a' => 'Yes. Full sheets and reasoning are free on Bao Predictions.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Jackpots', 'url' => '/jackpot-predictions']],
    ],
    'sportpesa-mega-jackpot-predictions' => [
        'title' => 'SportPesa Mega Jackpot Predictions | Bao Predictions',
        'description' => 'Accurate SportPesa Mega Jackpot predictions — 17 weekend games with pick, confidence and per-game reasoning. Updated this round.',
        'h1' => 'SportPesa Mega Jackpot Predictions',
        'canonical' => '/sportpesa-mega-jackpot-predictions',
        'unique' => 'This weekend\'s Mega Jackpot leans toward home favourites in the English and Spanish midday slots, with two tighter mid-card games that need careful cover rather than blind bankers. A 17-game ticket dies on its weakest link — which is why every row below carries a one-line reason tied to that fixture\'s form or matchup, not a generic "strong at home" line. Entry is typically from KES 99 on SportPesa; confirm the live prize pool and deadline in the app.',
        'related' => [
            ['All jackpot predictions', '/jackpot-predictions'],
            ['Mega Jackpot strategy guide', '/mega-jackpot-strategy-guide'],
            ['1X2 predictions', '/1x2-predictions'],
        ],
        'faqs' => [
            ['q' => 'How many games are in the SportPesa Mega Jackpot?', 'a' => 'Seventeen. You need every 1X2 correct to win the jackpot pool.'],
            ['q' => 'What happens if a match is postponed?', 'a' => 'SportPesa publishes settlement rules per round — postponed games are often voided or pushed. Check the app terms before kickoff.'],
            ['q' => 'When do Mega Jackpot predictions update?', 'a' => 'Usually Friday evening and again Saturday morning before the first kickoff.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Jackpots', 'url' => '/jackpot-predictions'], ['name' => 'SportPesa Mega', 'url' => '/sportpesa-mega-jackpot-predictions']],
    ],
    'sportpesa-midweek-jackpot-predictions' => [
        'title' => 'SportPesa Midweek Jackpot Predictions | Bao Predictions',
        'description' => 'SportPesa Midweek Jackpot predictions — 17 midweek games with confidence and reasoning. Smaller pool, free tips.',
        'h1' => 'SportPesa Midweek Jackpot Predictions',
        'canonical' => '/sportpesa-midweek-jackpot-predictions',
        'unique' => 'Midweek sheets mix Champions League leftovers with rearranged league fixtures — more variance than weekend Mega cards. Our anchors are European home favourites; domestic derbies are marked as swing games with capped confidence. Entry stakes are often lower than Mega (from around KES 49) but the pool is typically smaller. Do not reuse Saturday\'s Mega picks on this list — the fixture order and card differ.',
        'related' => [
            ['SportPesa Mega Jackpot', '/sportpesa-mega-jackpot-predictions'],
            ['Jackpot hub', '/jackpot-predictions'],
            ['HT/FT predictions', '/ht-ft-predictions'],
        ],
        'faqs' => [
            ['q' => 'How is Midweek different from Mega Jackpot?', 'a' => 'Both are 17-game 1X2 cards, but Midweek runs midweek with more cup/rearranged fixtures and usually a smaller prize pool.'],
            ['q' => 'What if a cup match goes to extra time?', 'a' => 'Jackpot markets usually settle on 90 minutes unless SportPesa states otherwise for that round.'],
            ['q' => 'Are midweek jackpot tips free?', 'a' => 'Yes.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Jackpots', 'url' => '/jackpot-predictions'], ['name' => 'SportPesa Midweek', 'url' => '/sportpesa-midweek-jackpot-predictions']],
    ],
    'betika-midweek-jackpot-predictions' => [
        'title' => 'Betika Midweek Jackpot Predictions | Bao Predictions',
        'description' => 'Betika Midweek Jackpot predictions — 15 games with picks and reasoning. Free Betika jackpot tips for this round.',
        'h1' => 'Betika Midweek Jackpot Predictions',
        'canonical' => '/betika-midweek-jackpot-predictions',
        'unique' => 'Betika\'s Midweek Jackpot is a 15-game card — not 17 — so hit probability is slightly kinder than SportPesa Midweek, though the pool is usually smaller. We treat Betika\'s published list as its own sheet: overlapping fixtures may share a lean, but order and confidence follow Betika\'s card. Expect more domestic leagues and fewer elite European ties than a UCL-heavy midweek.',
        'related' => [
            ['SportPesa Midweek Jackpot', '/sportpesa-midweek-jackpot-predictions'],
            ['Jackpot hub', '/jackpot-predictions'],
            ['Double chance predictions', '/double-chance-predictions'],
        ],
        'faqs' => [
            ['q' => 'How many games are in Betika Midweek Jackpot?', 'a' => 'Fifteen. All must be correct to win the jackpot.'],
            ['q' => 'Is it the same as SportPesa Midweek?', 'a' => 'No. Different bookmaker, different list, and Betika uses 15 games vs SportPesa\'s 17.'],
            ['q' => 'What if a Betika match is abandoned?', 'a' => 'Check Betika\'s jackpot terms for that round — abandoned matches are often voided from the card.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Jackpots', 'url' => '/jackpot-predictions'], ['name' => 'Betika Midweek', 'url' => '/betika-midweek-jackpot-predictions']],
    ],
    'sportybet-daily-jackpot-predictions' => [
        'title' => 'SportyBet Daily Jackpot Predictions | Bao Predictions',
        'description' => 'SportyBet Daily Jackpot predictions — today\'s short card with picks and confidence. Updated daily, free to view.',
        'h1' => 'SportyBet Daily Jackpot Predictions',
        'canonical' => '/sportybet-daily-jackpot-predictions',
        'unique' => 'SportyBet\'s daily product turns over every day with a shorter card (often around 10 selections) and lower entry stakes. Do not reuse yesterday\'s sheet — the list changes. Today\'s card is built around clear favourites plus a few trap fixtures we have marked under 60% confidence so you can see where the ticket is fragile before you submit.',
        'related' => [
            ['Jackpot hub', '/jackpot-predictions'],
            ['Today\'s predictions', '/football-predictions-today'],
            ['Sure bets today', '/sure-bets-today'],
        ],
        'faqs' => [
            ['q' => 'How many games are in SportyBet Daily Jackpot?', 'a' => 'It varies by day — often around 10. Confirm today\'s exact list in the SportyBet app.'],
            ['q' => 'When does it close?', 'a' => 'Before the first match on the card kicks off.'],
            ['q' => 'Is the daily jackpot easier to win?', 'a' => 'Fewer games improve hit probability vs 17-folds, but prize pools are smaller.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Jackpots', 'url' => '/jackpot-predictions'], ['name' => 'SportyBet Daily', 'url' => '/sportybet-daily-jackpot-predictions']],
    ],
    'odibets-laki-tatu-predictions' => [
        'title' => 'Odibets Laki Tatu Predictions | Bao Predictions',
        'description' => 'Odibets Laki Tatu predictions (odi laki tatu) — 3-game short jackpot picks with high-confidence leans. Verify live name in app.',
        'h1' => 'Odibets Laki Tatu Predictions',
        'canonical' => '/odibets-laki-tatu-predictions',
        'unique' => 'Laki Tatu is a short-card product — typically three selections — so strategy differs from a 17-game Mega sheet: selectivity beats coverage. We only publish games we rate strongly unless Odibets\' live card forces tougher slots. Odibets renames products periodically (Laki Tatu / Sababisha and similar); always confirm the current name and fixture count in the Odibets app before staking. Colloquial searches like "odi laki tatu predictions" refer to the same short-card intent.',
        'related' => [
            ['Jackpot hub', '/jackpot-predictions'],
            ['Must-win teams today', '/must-win-teams-today'],
            ['Mega Jackpot strategy guide', '/mega-jackpot-strategy-guide'],
        ],
        'faqs' => [
            ['q' => 'How many games are in Odibets Laki Tatu?', 'a' => 'Three in the classic product. Confirm the live offer in the Odibets app — naming changes over time.'],
            ['q' => 'Is Laki Tatu the same as Sababisha?', 'a' => 'Related short-card Odibets products. Fixture counts and branding can differ by promotion.'],
            ['q' => 'Why only three predictions?', 'a' => 'Short cards trade smaller absolute returns for higher hit probability than 15–17 game megas.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Jackpots', 'url' => '/jackpot-predictions'], ['name' => 'Laki Tatu', 'url' => '/odibets-laki-tatu-predictions']],
    ],
    'results' => [
        'title' => 'Prediction Results & Track Record | Bao Predictions',
        'description' => 'Bao Predictions results and track record — win rate, ROI, and settled tips including losses. Updated as matches finish.',
        'h1' => 'Results & Track Record',
        'canonical' => '/results',
        'unique' => 'Is Bao Predictions accurate? Judge the numbers — wins and losses — not slogans. This page publishes settled tips and rolling performance so you can verify us the same way bettors search "yesterday football predictions results" before trusting a tipster. We do not hide failed picks.',
        'related' => [
            ['Yesterday\'s results', '/football-predictions-yesterday'],
            ['How we predict', '/how-we-predict'],
            ['Today\'s predictions', '/football-predictions-today'],
        ],
        'faqs' => [
            ['q' => 'Do you publish losing tips?', 'a' => 'Yes. Losses appear alongside wins.'],
            ['q' => 'How often is ROI updated?', 'a' => 'As tips settle — see the last-updated stamp.'],
            ['q' => 'Is past performance a guarantee?', 'a' => 'No. Track record is historical only.'],
        ],
        'rg' => true,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'Results', 'url' => '/results']],
    ],
    'how-we-predict' => [
        'title' => 'How We Predict Football Tips | Bao Predictions',
        'description' => 'How Bao Predictions builds football tips — form, table context, market price, and honest confidence scores explained.',
        'h1' => 'How We Predict',
        'canonical' => '/how-we-predict',
        'unique' => 'Every public tip starts with recent results, competition context, and publicly reported injuries. Confidence is a 0–100 internal rating, not a promised win probability. We would rather show a low number than invent certainty — that is the opposite of scaled template spam Google\'s 2026 spam updates target.',
        'related' => [
            ['Results & track record', '/results'],
            ['About us', '/about-us'],
            ['Responsible betting', '/responsible-betting'],
        ],
        'faqs' => [
            ['q' => 'Is confidence a win probability?', 'a' => 'No. It is a relative strength score for that day\'s slate.'],
            ['q' => 'Do humans review tips?', 'a' => 'Yes. Automation helps gather fixtures; editors review headline leans and jackpot sheets.'],
            ['q' => 'Do you sell fixed matches?', 'a' => 'No. We do not offer fixed or guaranteed matches.'],
        ],
        'rg' => false,
        'crumbs' => [['name' => 'Home', 'url' => '/'], ['name' => 'How We Predict', 'url' => '/how-we-predict']],
    ],
];
